#Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: Dan Sadatian ðŸ“Š Data Science Manager
url: 'https://sadatian.io/'

#change it according to your repository name
# disabling since we are using a custom domain
# baseurl: '/resume' 

description: Data Science Manager driving enterprise ML/AI strategy, analytics platform integration, and high-performing technical teams. Military veteran bringing operational discipline and a passion for translating complex data into actionable business narratives. Currently leading analytics integration following the Capital Oneâ€“Discover merger, with expertise in context embedding, predictive analytics, and audit automation.
# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: ceramic # blue turquoise green berry orange ceramic
chrome_mobile_color: #use hex colors (ex:#1976d2) or leave empty if you don't want a color for chrome mobile searchbar

# Tracker
analytics:

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 0.0.0.0
safe: false
